spring:
  datasource:
       url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/pimba?autoReconnect=true&useSSL=false}
       username: ${DATASOURCE_USERNAME:root}
       password: ${DATASOURCE_PASSWORD:1234}
       driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    generate-ddl: true
    ddl-auto: update

park:
  base: park
  list: list
  coordinates: coordinates
  best: best

mapbox:
  token: pk.eyJ1IjoicGF1bG9zYW50b3NwaHMiLCJhIjoiY2oxN3k5NHhzMDZvdzJ3bXo5Nzh5ZGZlNCJ9.SjLN3Nwnqq0VnByM3f6wKQ

historic:
  base: historic
  register: register

evaluation:
  base: evaluation
  save: save

comment:
  base: comment
  save: save

common:
  base: common
  edit:
    base: edit
    name: name
    photo: photo
    phone: phone
    gender: gender
    city: city

vehicle:
  base: vehicle
  vehicles: vehicles
  register: register
  edit:
    base: edit
    name: name
    motor: motor
    brand: brand
    year: year
    licensePlate: licensePlate

login:
  facebook:
    app-id: 240904326376282
    app-secret: caa164498772b2e9804ae41e44142d3f
  token:
    header: Access-Token
    secret: shhhhhhh!!!!
    expiration: 604800
  route:
    authentication:
      base: auth
      signIn: login
      commonRegister: common
      customerRegister: customer
      refresh: refresh
      currentUser: me
      facebook:
        commonLogin: commonFacebook
        customerLogin: customerFacebook



