version: '2'
services:     
   pimba_webservice:
     image: pimba/pimba-back:latest
     restart: always
     environment:
       - "DATASOURCE_URL=jdbc:mysql://banco.ciqhsl2rupec.us-east-1.rds.amazonaws.com:3306/pimba?autoReconnect=true&useSSL=false"
       - "DATASOURCE_USERNAME=root"
       - "DATASOURCE_PASSWORD=s1st3m4h4rp1a:D"
     ports:
      - "8080:8080"
