version: '2'
services:     
   pimba_webservice:
     image: pimba/pimba-back:latest
     restart: always
     environment:
       - "DATASOURCE_URL=jdbc:mysql://104.154.103.78:3306/pimba?autoReconnect=true&useSSL=false"
       - "DATASOURCE_USERNAME=root"
       - "DATASOURCE_PASSWORD=p1mb@:D"
     ports:
      - "8080:8080"
